name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags: "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "Dockerfile"
      - "Dockerfile.wine"
      - supervisor/**
      - scripts/**
      - app/**
      - utils/**
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "Dockerfile.wine"
      - supervisor/**
      - scripts/**
      - app/**
      - utils/**
  workflow_dispatch:
    inputs:
      new_tag:
        description: "Create and use this tag (e.g. v1.2.3). Leave blank to skip."
        required: false
        default: ""
      push_latest:
        description: Push latest tag
        required: false
        type: boolean
        default: false

# Ensure we can push tags
permissions:
  contents: write

###############################################################################
# Job 1: Build winebase
###############################################################################
jobs:
  build-winebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      ################################################################
      # Step 1: Optionally create a new Git tag if triggered manually
      ################################################################
      - name: Create git tag (when workflow_dispatch + new_tag)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.new_tag != '' }}
        run: |
          echo "Creating and pushing tag '${{ github.event.inputs.new_tag }}'..."
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${{ github.event.inputs.new_tag }}"
          git push origin "${{ github.event.inputs.new_tag }}"

      ################################################################
      # Step 3: Build the list of Docker tags for winebase
      ################################################################
      - name: Generate Docker tag list (winebase)
        id: taglist-winebase
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: |
          IMAGE_NAME="winebase"

          # Start with empty string
          tag_list=""

          # Always include short commit
          tag_list+="$DOCKER_USER/winebase:${{ env.COMMIT_SHA_SHORT }}"

          # If we have a branch name, add it
          if [ -n "${{ env.BRANCH_NAME }}" ]; then
            tag_list+=$'\n'"$DOCKER_USER/winebase:${{ env.BRANCH_NAME }}"
          fi

          # If we have a semver/user tag (i.e. DOCKER_IMAGE_TAG is set and not empty), add it
          if [ -n "${{ env.DOCKER_IMAGE_TAG }}" ]; then
            tag_list+=$'\n'"$DOCKER_USER/winebase:${{ env.DOCKER_IMAGE_TAG }}"
          fi

          # Optionally include the "latest" tag
          if [[ "${{ env.PUSH_LATEST }}" == "true" ]]; then
            tag_list+=$'\n'"$DOCKER_USER/winebase:latest"
          fi

          echo "tag_list=$tag_list" >> $GITHUB_OUTPUT
          echo "::notice file=.github/workflows/docker-image.yml,line=94,endLine=94,title=Generated Docker tags for winebase::$tag_list"


      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build & push winebase image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile.wine
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.taglist-winebase.outputs.tag_list }}

  ###############################################################################
  # Job 2: Build grlevelx (needs winebase)
  ###############################################################################
  build-grlevelx:
    runs-on: ubuntu-latest
    needs: build-winebase  # <-- This ensures grlevelx waits for winebase
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Generate Docker tag list (grlevelx)
        id: taglist-grlevelx
        run: |
          tag_list=""

          # Always include short commit
          tag_list+="${{ secrets.DOCKER_HUB_USER }}/grlevelx:${{ env.COMMIT_SHA_SHORT }}"

          # If we have a branch name, add it
          if [ -n "${{ env.BRANCH_NAME }}" ]; then
            tag_list+=$'\n'"${{ secrets.DOCKER_HUB_USER }}/grlevelx:${{ env.BRANCH_NAME }}"
          fi

          # If we have a semver/user tag, add it
          if [ -n "${{ env.DOCKER_IMAGE_TAG }}" ]; then
            tag_list+=$'\n'"${{ secrets.DOCKER_HUB_USER }}/grlevelx:${{ env.DOCKER_IMAGE_TAG }}"
          fi

          # Optionally include the "latest" tag
          if [[ "${{ env.PUSH_LATEST }}" == "true" ]]; then
            tag_list+=$'\n'"${{ secrets.DOCKER_HUB_USER }}/grlevelx:latest"
          fi

          echo "tag_list=$tag_list" >> $GITHUB_OUTPUT
          echo "::notice file=.github/workflows/docker-image.yml,line=151,endLine=151,title=Generated Docker tags for grlevelx::$tag_list"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build & push grlevelx image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: WINE_TAG=${{ env.COMMIT_SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.taglist-grlevelx.outputs.tag_list }}
