name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: false
        default: "v0.0.0"

jobs:
  build-docker-images:
    # Prevent multiple runs from colliding (optional).
    concurrency:
      group: docker-image-ci-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # You can give a friendly name, Dockerfile path, or Docker repo name as you like
        include:
          - name: winebase
            dockerfile: Dockerfile.wine
          - name: grlevelx
            dockerfile: Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Detect Docker image tags
        id: detect
        run: |
          # If this is a tag push (refs/tags/vX.Y.Z) -> use that tag
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "COMMIT_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
            echo "DOCKER_IMAGE_TAG=$(echo ${{ github.ref_name }} )" >> $GITHUB_ENV
          else
            # Otherwise, default to the short SHA
            echo "COMMIT_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
            echo "DOCKER_IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push ${{ matrix.name }} image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=docker.io/professorcha0s/${{ matrix.name }}:${{ env.COMMIT_SHA_SHORT }}
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.name }}:${{ env.COMMIT_SHA_SHORT }}
            ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.name }}:${{ env.DOCKER_IMAGE_TAG }}
